[package]
name = "klsp"
version = "0.1.0"
edition = "2021"

[dependencies]
lsp-server = "0.7.4"
lsp-types = "0.94.1"
tokio = { version = "1.34.0", features = ["full"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
regex = "1.10.2"

